import type { AnalysisResult, MentorGrounding, ScoreBand, StructuredResume } from "../types";
import { isCustomRoleName } from "./constants";

/** Score band per UI.md: 0-49 danger, 50-79 warning, 80-100 success. */
export function scoreBand(score: number): ScoreBand {
  if (score < 50) return "danger";
  if (score < 80) return "warning";
  return "success";
}

const BAND_COLORS: Record<ScoreBand, string> = {
  danger: "#DC2626",
  warning: "#D97706",
  success: "#16A34A",
};
export function bandColor(band: ScoreBand): string {
  return BAND_COLORS[band];
}
export function scoreColor(score: number): string {
  return bandColor(scoreBand(score));
}

/** Qualitative readiness label (UI.md Readiness card). */
export function readinessLabel(score: number): string {
  if (score < 50) return "Early";
  if (score < 80) return "On track";
  return "Interview-ready";
}

/**
 * Build the deterministic grounding the client sends to /api/mentor.
 * Sends ONLY { targetRole, structuredResume, matchObject, rawResumeText } — the
 * server reconstructs health/readiness/roadmap internally.
 */
export function buildGrounding(
  analysis: AnalysisResult,
  structuredResume: StructuredResume,
  rawResumeText: string,
): MentorGrounding {
  return {
    targetRole: analysis.targetRole,
    structuredResume,
    matchObject: analysis.matchObject,
    rawResumeText,
    // Lets the server allow the grounded mentor to operate on a custom
    // job-posting role that isn't in roles.json.
    fromJobPosting: isCustomRoleName(analysis.targetRole),
  };
}

/** Plain-text summary for the "Copy Summary" clipboard action (no PDF). */
export function formatPlainSummary(a: AnalysisResult): string {
  const { matchObject: m, readiness: r, resumeHealth: h, roadmap, targetRole } = a;
  const lines: string[] = [];

  lines.push(`CareerPilot — Resume Analysis`);
  lines.push(`Target Role: ${targetRole}`);
  lines.push("");
  lines.push(`Career Readiness: ${r.score}/100 (${readinessLabel(r.score)})`);
  lines.push(
    `Skill Coverage: ${m.coveragePercentage}% — ${m.have.length}/${m.requiredSkills.length} required skills`,
  );
  lines.push(`Resume Health: ${h.overall}/100`);
  lines.push("");

  lines.push(`Skills you have: ${m.have.join(", ") || "(none)"}`);
  lines.push(`Skills to learn: ${m.missing.join(", ") || "(none — all covered!)"}`);
  lines.push("");

  if (r.strengths.length) {
    lines.push("Strengths:");
    r.strengths.forEach((s) => lines.push(`  • ${s}`));
    lines.push("");
  }
  if (r.nextActions.length) {
    lines.push("Next actions:");
    r.nextActions.forEach((s) => lines.push(`  → ${s}`));
    lines.push("");
  }
  if (roadmap.length) {
    lines.push("24-Week Roadmap:");
    roadmap.forEach((mi) =>
      lines.push(`  ${mi.phase}: ${mi.skill} — ${mi.project} (${mi.resource})`),
    );
  }

  lines.push("");
  lines.push("Generated by CareerPilot · deterministic, grounded, evidence-based.");
  return lines.join("\n");
}
